# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpoisVector <- function(n, seed, mu) {
    .Call('testPkg_rpoisVector', PACKAGE = 'testPkg', n, seed, mu)
}

runifVector <- function(n, seed) {
    .Call('testPkg_runifVector', PACKAGE = 'testPkg', n, seed)
}

